routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth', 'namespace' => 'App'], function () {
  Route::get('/dashboard', 'DashboardController@index');
  Route::get('/users/table', 'UserController@table')->name('users.table');
  Route::resource('users', 'UserController');
});

Route::group(['namespace' => 'Auth'], function(){
  //invite
  Route::post('/invite', 'InviteController@invite');
  Route::get('/invite/form', 'InviteController@form');
  Route::post('/invite/accept', 'Invitecontroller@accept');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Traits\HasPermissions;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function company(){
      return $this->belongsTo('App\Company');

    }
}

app/Http/Controllers/Api/V1/UserController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;

use App\Repositories\UserRepository as Users;
use App\Traits\InviteTrait;

use Input;

class UserController extends ApiV1Controller
{
	use InviteTrait;

	private $users;

	public function __construct(Users $users)
	{
			$this->users = $users;
	}

	public function index(){
		$company_users = $this->users->get_company_users();
		return response()->json(['users' => $company_users], 200);
	}

	public function invite(){
		$input = Input::all();
		$validator = $this->users->validate_invite($input);
		if($validator->fails()){
			return response()
				->json(['success' => false, 'input' => $input, 'errors' => $validator->errors()]);
		}

		$this->SendInvite($input['email']);

		return response()->json(['success' => true]);
	}

}

app/Http/Controllers/App/UserController.php
<?php

namespace App\Http\Controllers\App;

use Illuminate\Http\Request;

use App\Repositories\UserRepository as Users;
use App\Repositories\InviteRepository as Invites;
use Spatie\Permission\Models\Permission;

use App\Http\Requests;
use Auth;
use Datatables;

class UserController extends AppController
{
    protected $view_prefix = 'app.users.';
    private $users;
    private $invites;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Users $users, Invites $invites)
    {
        $this->middleware('auth');
        $this->users = $users;
        $this->invites = $invites;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view($this->view_prefix . __FUNCTION__);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $view_data['user'] = $this->users->find($id);
      $view_data['permissions'] = Permission::all();
      return view($this->view_prefix . __FUNCTION__, $view_data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      switch($request->input('action')){
        case "user":
          return $this->update_user($request->input('user'), $id);
        break;
        case "password":
          return $this->update_password($request->input('password'), $id);
        break;
        case "permissions":
          return $this->update_permissions($request->input('permissions'), $id);
        break;
      }
    }

    public function update_user($data, $id){

      $validator = $this->users->validation($data, $id);
      if($validator->fails())
      {
        return redirect()
          ->back()
          ->withErrors($validator)
          ->withInput();
      }
      $this->users->update($data, $id);
      return redirect()->route('users.edit', ['user' => $id])->with('message', trans('message.updated', array('object' => trans('user'))));
    }

    public function update_password($data, $id){
      $validator = $this->users->validation_password($data);
      if($validator->fails()){
        return redirect()
          ->back()
          ->withErrors($validator)
          ->withInput();
      }
      $this->users->update_password($data, $id);
      return redirect()->route('users.edit', ['user' => $id])->with('message', trans('message.updated', array('object' => trans('user'))));
    }

    public function update_permissions($data, $id) {
      $this->users->syncPermissions($id, $data);
      return redirect()->route('users.edit', ['user' => $id])->with('message', trans('message.updated', array('object' => trans('user'))));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = $this->users->find($id);
        $this->invites->deleteCompanyInvite($user->email);
        $this->users->delete($id);
        toast()->message(trans('common.delete_success'), 'success', 'Success');
        return redirect()->route('users.index');
    }

    public function table(){
      $company_users = $this->users->get_company_users();

      return Datatables::of($company_users)
      ->addColumn('action', function ($user) {
        $edit_button = (string) view('common.buttons.button', array('href' => route('users.edit', $user->id), 'title' => 'Edit'));
        $delete_button = (string) view('common.buttons.delete', array(
          'href' => route('users.destroy', $user->id),
          'title' => 'Delete',
          'type' => 'btn-danger',
          'confirm' => array(
            'title' => trans('common.confirm_delete'),
            'text' => trans('common.confirm_delete_text', array('object' => trans('user'))),
            'buttontext' => trans('common.confirm_delete_buttontext'),
            'type' => 'warning',
          )
        ));

        if($user->hasRole('Master')){
          return $edit_button;
        }
        else{
          return $edit_button . $delete_button;
        }
      })
      ->make(true);
    }
}

resources/views/app/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <div class="title">@lang('common.users.edit', ['name' => $user->name])</div>
        </div>
      </div>
      <div class="card-body no-padding">
        <div role="tabpanel">
          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active"><a href="#user_data" aria-controls="user_data" role="tab" data-toggle="tab">@lang('common.user_data')</a></li>
              <?php if(Auth::user()->hasRole('Master') || Auth::user()->hasPermissionTo('Manage users')): ?>
                <li role="presentation"><a href="#user_permissions" aria-controls="user_permissions" role="tab" data-toggle="tab">@lang('common.user_permissions')</a></li>
              <?php endif; ?>
          </ul>
          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="user_data">
              <div class="sub-title">@lang('common.update_user')</div>
        			<form class="form-horizontal" role="form" method="POST" action="{{ route('users.update', ['user' => $user->id]) }}">
        	      {{ csrf_field() }}
                <input name="_method"  type="hidden" value="PATCH">
        				<input type="hidden" name="action" value="user">
        				<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                  <label for="email" class="col-sm-2 control-label">@lang('common.email')</label>
                  <div class="col-sm-10">
                    {{ old('email') }}
                    <input type="email" name="user[email]" class="form-control" id="email" placeholder="@lang('common.email')" value="@if(!empty(old('email'))) old('email') @else {{ $user->email }} @endif">
                    @if ($errors->has('email'))
        								<span class="help-block">
        										<strong>{{ $errors->first('email') }}</strong>
        								</span>
        						@endif
                  </div>
              	</div>
        				<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                  <label for="name" class="col-sm-2 control-label">@lang('common.name')</label>
                  <div class="col-sm-10">
                    <input type="text" name="user[name]" class="form-control" id="name" placeholder="@lang('common.name')" value="{{$user->name}}">
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                  </div>
              	</div>
        				<div class="form-group">
        					<div class="col-sm-10 col-sm-offset-2">
                  	<input type="submit" value="@lang('common.update')" class="btn btn-primary">
        					</div>
              	</div>
        			</form>
              <div class="sub-title">@lang('common.update_password')</div>
        			<form class="form-horizontal" role="form" method="POST" action="{{ route('users.update', ['user' => $user->id]) }}">
        	      {{ csrf_field() }}
                <input name="_method" type="hidden" value="PATCH">
        				<input type="hidden" name="action" value="password">
        				<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                  <label for="email" class="col-sm-2 control-label">@lang('auth.password')</label>
                  <div class="col-sm-10">
                    <input type="password" name="password[password]" class="form-control" id="email" placeholder="@lang('auth.password')" >
                    @if ($errors->has('password'))
                        <span class="help-block">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
                  </div>
              	</div>
        				<div class="form-group">
                  <label for="name" class="col-sm-2 control-label">@lang('auth.confirm_password')</label>
                  <div class="col-sm-10">
                    <input type="password" name="password[password_confirmation]" class="form-control" id="name" placeholder="@lang('auth.confirm_password')">
                  </div>
              	</div>
        				<div class="form-group">
        					<div class="col-sm-10 col-sm-offset-2">
                  	<input type="submit" value="@lang('common.update')" class="btn btn-primary">
        					</div>
              	</div>
        			</form>
            </div>
            <?php if(Auth::user()->hasRole('Master') || Auth::user()->hasPermissionTo('Manage users')): ?>
              @include('app.users.partials.permissions_tab', ['user' => $user, 'permissions' => $permissions])
            <?php endif; ?>
          </div>
        </div>
      </div>
		</div>
  </div>
</div>
@endsection

resources/views/app/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <div class="title">@lang('common.users')</div>
        </div>
        <div class="pull-right card-action">
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i> <span class="caret"></span></button>
            <ul class="dropdown-menu" role="menu">
              <li><a data-toggle="modal" data-target="#modal_user_invite">Invite new user</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="card-body">
        <table id="datatable-table" class="table table-striped datatable" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Action</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="modal_user_invite" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">@lang('auth.invite_modal_title')</h4>
      </div>
      <form role="form" method="POST" action="{{ url('/invite') }}">
      <div class="modal-body">
          {{ csrf_field() }}
          <div class="control">
            <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" autofocus placeholder="@lang('auth.email')">
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">@lang('common.close')</button>
        <button type="submit" class="btn btn-primary">@lang('auth.invite_user')</button>
      </div>
      </form>
    </div>
  </div>
</div>
@endsection
@push('scripts')
<script>
$(function() {
    $('#datatable-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route("users.table") !!}',
        columns: [
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            { data: 'action', name: 'action', orderable: false, searchable: false},
        ],
    });
});
</script>
@endpush